exclude: ".terraform/"
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.1
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
        alias: terraform_tflint_nocreds
        name: terraform_tflint_nocreds
        exclude: "^examples/"
        args:
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
  - repo: local
    hooks:
      - id: terraform_docs
        name: Terraform Docs
        entry: terraform-docs .
        language: system
        files: \.tf.*$
        types_or:
          - terraform
          - markdown
        pass_filenames: false

      - id: terraform_validate
        name: terraform_validate
        entry: |
          bash -c '
            AWS_DEFAULT_REGION=us-east-1
            declare -a DIRS
            for FILE in "$@"
            do
              DIRS+=($(dirname "$FILE"))
            done
            for DIR in $(printf "%s\n" "${DIRS[@]}" | sort -u)
            do
              cd $(dirname "$FILE")
              terraform init --backend=false
              terraform validate .
              cd ..
            done
          '
        language: system
        verbose: true
        files: \.tf(vars)?$
        exclude: examples
      # - id: tflock
      #   name: provider_locks
      #   entry: |
      #     bash -c '
      #       AWS_DEFAULT_REGION=us-east-1
      #       declare -a DIRS
      #       for FILE in "$@"
      #       do
      #         DIRS+=($(dirname "$FILE"))
      #       done
      #       for DIR in $(printf "%s\n" "${DIRS[@]}" | sort -u)
      #       do
      #         cd $(dirname "$FILE")
      #         terraform providers lock -platform=windows_amd64 -platform=darwin_amd64 -platform=linux_amd64 -platform=darwin_arm64 -platform=linux_arm64
      #         cd ..
      #       done
      #     '
      #   language: system
      #   verbose: true
      #   files: \.tf(vars)?$
      #   exclude: examples
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: no-commit-to-branch
        args:
          - --branch
          - main
          - --branch
          - master
          - --branch
          - prod
      - id: pretty-format-json
        args:
          - --autofix
          - --top-keys=name,Name
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
        exclude: README.md
ci:
  skip:
    - tflock
